spring.application.name=users
spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.username=test
spring.r2dbc.password=test

spring.sql.init.mode=embedded

token.secret=xsi8x9m6yv9bqz53zarizgsr8jaqgf884ibz1gpteulfvuic47oxmvxb4iq7y51v